version: '3'
services:
  # Backend service
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./backend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  # Frontend service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app   
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

# Define a custom network
networks:
  app-network:
    driver: bridge
